name: ifconfighw
version: 0.1.0.0
github: "satosystems/ifconfighw"
license: BSD3
author: "Satoshi Ogata"
maintainer: "satosystems@gmail.com"
copyright: "(c) 2022 Satoshi Ogata"

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: ifconfig wrapper
category: CLI

description: Please see the README on GitHub at <https://github.com/satosystems/ifconfighw#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ifconfighw:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ifconfighw

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ifconfighw
